# CephDeployer
Vagrant.configure("2") do |config|
 # define the os version of this box
  config.vm.box = "ubuntu/trusty64"
 # define the hostname
  config.vm.hostname = "CephDeployer"
 # define the networking 
  config.vm.network :private_network, ip: "192.168.56.10"
  config.vm.network :public_network 
 # install the dependency
  config.vm.provision "shell", path: "script.sh"
end
