# CephDeployer
Vagrant.configure("2") do |config|
 # define the os version of this box
  config.vm.box = "ubuntu/trutsty64"
 # define the hostname
  config.vm.hostname = "CephDeployer"
 # define the networking 
  config.vm.network :private_network, ip: "192.168.56.10"
  config.vm.network :public_network, bridge: 
 # install the dependency
 	wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
 	sudo apt update
 	sudo apt install ceph-deploy
end